make the ramdisk feature functional
minosproject/minos pull request #35
Opened 2020-12-24 07:22 UTC by l3ifeng

- map vm region
- get ramdisk from fdt
- copy fdt before setup vm
- copy kernel before start vm
- add a script that can make ramdisk

2020-12-24 08:47 UTC, lemin9538 requested changes

2020-12-24 08:47 UTC, lemin9538 commented on virt/vm.c
> +		ramdisk_read(&vm->image_file, vm->entry_point,
有种case 这个地方可能会有问题。zephyr os 的entry address和load address不一样。直接以entry address 作为load address 会出问题。

2020-12-24 08:47 UTC, lemin9538 commented on include/common/hypervisor.h
> +	char image_file[RAMDISK_FNAME_SIZE];
这个地方有个风险是：当前分配的栈空间是8192, 在create_native_vm_of时，vmtag是分配在栈上的，如果函数调用链比较深，有栈溢出的风险。

2020-12-24 08:59 UTC, l3ifeng commented on virt/vm.c
> +		ramdisk_read(&vm->image_file, vm->entry_point,
@lemin9538 So we need a "load-address"?

2020-12-24 09:01 UTC, l3ifeng commented on include/common/hypervisor.h
> +	char image_file[RAMDISK_FNAME_SIZE];
@lemin9538 256 is too long as a file name, 64 should be fine?

2020-12-24 09:04 UTC, lemin9538 commented on include/common/hypervisor.h
> +	char image_file[RAMDISK_FNAME_SIZE];
我觉得64可以的，make_ramdisk.sh脚本里面可以加个提示，如果文件名过大提示下被截取。

2020-12-24 09:05 UTC, lemin9538 commented on virt/vm.c
> +		ramdisk_read(&vm->image_file, vm->entry_point,
是的 我觉得需要一个load_address, 如果load_address没有设定的话 load_address = entry_address.

2020-12-25 14:15 UTC, lemin9538 requested changes
总体我认为差不多了，再把ramdisk memory region处理相关代码加上就可以了。

2020-12-25 14:15 UTC, lemin9538 commented on core/minos.c
> +#ifdef CONFIG_DEVICE_TREE
这个放在fdt_parse_memory_info函数里面更好点。在fdt_parse_memory_info实现新的fdt_parse_ramdisk_memory(),同时解析ramdisk的内存区域。

2021-01-15 13:41 UTC, lemin9538 commented
I update this patch by another PR. so close this one.

2021-01-15 13:41 UTC, closed without merging